controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /news/21
    controller: App\Controller\DetailPageController::index
    methods: GET